[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
preDeployCommand = "sh railway-migrate.sh"
startCommand = "sh railway-start.sh"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/up"
healthcheckTimeout = 300
